### PR TITLE
smooth scrolling

### PR DESCRIPTION
**Pull request by d-a-v**
* Smooth scrolling on every display type
* example
* [demo](https://youtu.be/IpTwbLtGfuc) on 64x48 display

### CODE REVIEW

**Comment by greiman** [comment]
I don't have time to look at this more now.  I had problems in some of my apps with using it with smooth scrolling disabled.

I am planing several new features probably in a few months when I have time.  I will look at it again then.

The smooth scrolling example seem way too complicated.  Maybe there are primitives that would make it simpler.  Perhaps with less of the code in the library.

Also I need a #define macro so the size of the library will not be increased for 128x64 displays with scrolling enabled.  Lots of people have apps on Uno that are at the absolute limit of flash.

**Comment by greiman** [comment]
I have decided I don't want to use your implementation for scrolling on displays with fewer than eight rows.

My scrolling for eight row displays was a fast hack.  I should have managed the display to memory map so the cursor position is relative to the display, not memory.  I will define m_pageOffset and use it like m_colOffset.

Then setRow will be something like this for all cases.

```
void SSD1306Ascii::setRow(uint8_t row) {
  if (row >= m_displayHeight/8) return;
  m_row = row;
  ssd1306WriteCmd(SSD1306_SETSTARTPAGE | ((m_row + m_pageOffset ) % 8));
}
```
I will consider smooth scrolling after I finish this mod.

**Comment by d-a-v** [comment]
I will update my repo to try and fit small uC requirements (ram and flash footprint on at328p),
I will add trivial examples.
Regarding `m_pageOffset` I can rename my `m_top` since it *is* the page offset  and `setRow` is really like yours (cursor position is relative to the visible part of the display):
```
ssd1306WriteCmd(SSD1306_SETSTARTPAGE | ((m_row + m_top) % 8));
```
Letting to set row to something further the last displayable line allows to hide new lines that will be later smoothly scrolled to visible viewport (when using smaller than 64 lines displays).
I will remove my conditional disabling `m_row` checking and add this instead:
```
if (row >= 8) return
``` 

> I have decided I don't want to use your implementation for scrolling on displays with fewer than eight rows.

If the reason is ram and flash footprint, please allow me some more time before closing.
I believe smaller displays should not be left aside. Scrolling on them can hopefully be as cheap (footprint) as with large displays and I'll work on that.

**Comment by greiman** [comment]
I tried to implement smooth scrolling for data displays in some of my apps using your primitives. 

Doing simple things like writing an eight row message to memory and continuously rolling it on a four row display between message updates is not easy.  I just don't find the process() idea very flexible.

I fixed a number of bugs, revise the code so the cursor is defined relative to a window in RAM, and implemented an alternate set of primitives.   

The result, with support for all display sizes, is about 60 bytes smaller than the current code for only eight row displays.  The INCLUDE_SCROLLING_SMOOTH macro is not required.

I modified your example and used the new primitives  in several of my apps.

Here are the new member functions and scrolling modes.
```
// No scrolling.
#define SCROLL_MODE_OFF  0
// Newline causes map of new memory pages and setStartLine.
#define SCROLL_MODE_AUTO 1
// Newline only causes map of new memory pages.
#define SCROLL_MODE_APP  2

uint8_t pageOffset() {return m_pageOffset;}
uint8_t pageOffsetLine() {return 8*m_pageOffset;}  
void scrollDisplay(int8_t lines) {setStartLine(m_startLine + lines);}
bool scrollIsSynced() {return startLine() == pageOffsetLine();}
void scrollMemory(int8_t pages) {setPageOffset(m_pageOffset + pages);}
void setPageOffset(uint8_t page);   
void setScrollMode(uint8_t mode) {m_scrollMode = mode;}
void setStartLine(uint8_t line);
uint8_t startLine() {return m_startLine;}

void setScroll(bool enable) __attribute__((deprecated("use setScrollMode")));
```
Here is the code for setRow and the new functions.

```
//------------------------------------------------------------------------------
void SSD1306Ascii::setRow(uint8_t row) {
  if (row >= m_displayHeight/8) return;
  m_row = row;
#if INCLUDE_SCROLLING
  ssd1306WriteCmd(SSD1306_SETSTARTPAGE | ((m_row + m_pageOffset) & 7));
#else
  ssd1306WriteCmd(SSD1306_SETSTARTPAGE | m_row);
#endif  // INCLUDE_SCROLLING
}
#if INCLUDE_SCROLLING
//------------------------------------------------------------------------------
void SSD1306Ascii::setPageOffset(uint8_t page) {
  m_pageOffset = page & 7;
  setRow(m_row);
}
//------------------------------------------------------------------------------
void SSD1306Ascii::setStartLine(uint8_t line) {
  m_startLine = line & 0X3F;
  ssd1306WriteCmd(SSD1306_SETSTARTLINE | m_startLine);
}
```

Here is a modified version of your example.
```
#define I2C_ADDRESS 0x3C

#include <Wire.h>
#include <SSD1306Ascii.h>
#include <SSD1306AsciiWire.h>

SSD1306AsciiWire oled;

int count;
int len;
int dir;
int lines;
const char* text;

const char down [] = "Hello";
const char up   [] = "Scrworld";

const uint8_t* fontlist[] =
{
  System5x7,
  Wendy3x5,
  Verdana12_italic,
  TimesNewRoman13,
  0
};
int font;

void resetscroll ()
{
  static int state = -1;
  state++;
  
  if (state & 4)
    oled.set2X();
  else
    oled.set1X();

  if (state == 8)
  {
    if (!fontlist[++font])
      font = 0;
    oled.setFont(fontlist[font]);
    state = 0;
  }

  lines = oled.displayRows() / oled.fontRows();
  if (lines <= 2)
    Serial.println(F("font too big for scrolling"));
  dir = -dir;
  // Set to first or last line
  oled.setCursor(0, dir < 0 ? 0 : oled.displayRows() - oled.fontRows());
  text = dir > 0 ? down : up;
  len = strlen(text);
  count = 0;
}

void setup ()
{
  Serial.begin(9600);

  Wire.begin();
  Wire.setClock(400000L);

  oled.begin(&MicroOLED64x48, I2C_ADDRESS);

  oled.setFont(fontlist[font = 0]);
  
  // Not needed since newline will not scroll display.
  // oled.setScrollMode(SCROLL_MODE_AUTO);

  oled.clear();

  oled.print("Smooth\n\nScrolling\n\ndemo");
  delay(3000);

  dir = -1;
  resetscroll();
}
uint32_t scrollTime = 0;
void loop ()
{
  if (!oled.scrollIsSynced()) {
    uint32_t now = millis();
    if ((now - scrollTime) >= 10) {
      oled.scrollDisplay(dir);
      scrollTime = now;
    }
  } else {
    if (count > len + lines)
      resetscroll();
      
   // Set RAM page map
   oled.scrollMemory(dir*oled.fontRows());  
   oled.setCol(0);
   
    if (count < len)
    {
      oled.write("- ");
      oled.write(text[count]);
      oled.write(" -");
    }
    oled.clearToEOL();
    count++;
  }
}
``````

**Comment by greiman** [comment]
Here is the test program that just rolls an eight line message.
```
#include <Wire.h>
#include "SSD1306Ascii.h"
#include "SSD1306AsciiWire.h"

// 0X3C+SA0 - 0x3C or 0x3D
#define I2C_ADDRESS 0x3C

SSD1306AsciiWire oled;

void setup() {
  Wire.begin();
  Wire.setClock(400000L);
  oled.begin(&MicroOLED64x48, I2C_ADDRESS);

  oled.setFont(System5x7);
  oled.clear();
  // Application will handle scrolling.
  oled.setScrollMode(SCROLL_MODE_APP);
  for (int i = 0; i < 8; i++) {
    if (i) oled.println();
    oled.print("Line ");
    oled.print(i + 1);
  }
}

uint32_t scrollTime;
void loop() {
  uint32_t now = millis();
  if ((now - scrollTime) > 50) {
    // Scroll one line.
    oled.scrollDisplay(1);
    scrollTime = now;
  }
  // do other stuff
}
```

**Comment by d-a-v** [comment]
I understand you've spent time on this. Your interest is much appreciated.
As I found no dev branch on your repository to work with, I am now trying to figure out if it is needed that I further update my PR to fit with your direction, or if I need to wait for the next version.
FWIW I fixed a bug and added a scrolling story example.

Your new API and the example update look very good to me.
Although I'd still prefer using the ::process(ms) because it makes the final sketch easier to read, I guess I can do that myself (in sketch) by extending the class (though easier if `private` is changed to `protected`).

After re-reading your API and the updated example, this method is a lot simplified. It could be an inline method that would take no flash space when not used. 

```
...
inline bool canProcessNewLine (unsigned long& scrollTime, uint16_t delay, int8_t direction)
{
  if (scrollIsSynced())
    return true;

  unsigned long now = millis();
  if ((now - scrollTime) >= delay) {
    scrollTime = now;
    scrollDisplay(dir);
  }
  return false;
}
```

The modified example would become:
```
void loop ()
{
  if (oled.canProcessNewLine(scrollTime, 10)) {
    if (count > len + lines)
      resetscroll();
...
```

**Comment by d-a-v** [comment]
> The result, with support for all display sizes, is about 60 bytes smaller than the current code for only eight row displays. 

Congrats for this!

**Comment by greiman** [comment]
I like the idea of using protected.  I should also make most values of private/protected variables available in libraries and allow setting variable with error checking when possible.

I was surprised at the popularity of SSD1306Ascii.  I wrote it when I decided to move from big old LCD displays to small OLED displays in my data logging apps.

Existing SSD1306 libraries had a 1 KB buffer to support graphics.  This made it impossible to use my SdFat library with OLED displays on 328 Arduino boards.

I posted it, thinking few would use it, since there are so many OLED libraries.

I still resist adding features since my goal was to replace LCD displays in complex apps on Uno and other small boards.  

Even if features don't take memory when not used, they make the documentation more complex and confusing for users who just want LCD functionality.

**Comment by d-a-v** [comment]
I originally made my unbufferred ssd1306 ascii library too.
Then I added scrolling.
Then I added smooth scrolling.
Then I discovered your library which is much more advanced (and popular, meaning also quality).
This is why I wanted to port this feature.
Thanks for maintaining it the KISS way.

**Comment by d-a-v** [comment]
The flash and ram size informations compared with other buffered libraries should go into the main README.md !

**Comment by greiman** [comment]
I pushed a new version, 1.2.0.  Hope I didn't break too much.  I got carried away with cleanup.

I used your idea in the SmoothScrollWire example.  I tried to make it work with 32 and 48 high displays.  I gave you credit for the idea and I get blame for the implementation.  It is way too complex for most Arduino users.

I suggest reading the SSD1306 datasheet.  I suspect few users will look at the datasheet.

I just noticed I left an unneeded Serial.begin() in the program. I will remove it in the next version.

I added a simple example with smooth scrolling, SlowScrollWire.

**Comment by greiman** [comment]
Posted 1.2.1 but didn't tag it yet for the Arduino library manager.

**Comment by d-a-v** [comment]
Thanks for 1.2.x, Thanks for your support, it works for me.
 
FWIW, here's the SmoothScrollWire sketch with the inheriting class:
```
#include <Wire.h>
#include "SSD1306Ascii.h"
#include "SSD1306AsciiWire.h"

// 0X3C+SA0 - 0x3C or 0x3D
#define I2C_ADDRESS 0x3C

class OLED: public SSD1306AsciiWire
{
  public:

    OLED(): SSD1306AsciiWire(), scrollTime(0)  { }

    bool isReady (unsigned int ms, int dir)
    {
      unsigned long now = millis();
      if (!scrollIsSynced()) {
        if ((now - scrollTime) >= ms) {
          // Scroll display window.
          scrollDisplay(dir);
          scrollTime = now;
        }
        return false;
      }
      return (now - scrollTime) > ms;
    }

  protected:
    unsigned long scrollTime;
};

OLED oled;

int blank = 0; // Count of blank lines.
int count = 0; // Count of displayed lines.
int dir = 1;   // Scroll direction.
//------------------------------------------------------------------------------
void setup () {
  Serial.begin(9600);
  Wire.begin();
  Wire.setClock(400000L);

  oled.begin(&MicroOLED64x48, I2C_ADDRESS);
  oled.setFont(System5x7);
  oled.clear();

  // Not really needed since newline will not scroll the display in this example.
  oled.setScrollMode(SCROLL_MODE_APP);

  oled.print("Smooth\nScrolling\ndemo");
  delay(3000);

  // Set cursor to last row of window.
  oled.setRow(oled.displayRows() - oled.fontRows());
}
//------------------------------------------------------------------------------
void loop () {
  if (oled.isReady(15, dir)) {
    // Done if screen is blank.
    if (blank * oled.fontRows() > oled.displayRows()) {
      // Set new direction and magnification.
      blank = 0;
      count = 0;
      // Reverse scroll direction.
      dir = -dir;
      // Set font magnification.
      if (dir > 0) {
        if (oled.magFactor() == 1) {
          oled.set2X();
        } else {
          oled.set1X();
        }
      }
      // Set cursor to first or last line of memory window.
      oled.setCursor(0, dir < 0 ? 0 : oled.displayRows() - oled.fontRows());
    }
    // Scroll memory window.
    oled.scrollMemory(dir * oled.fontRows());
    oled.setCol(0);
    if (count * oled.fontRows() <= oled.displayRows()) {
      oled.print(dir < 0 ? "DN " : "UP ");
      oled.print(++count);
    } else {
      blank++;
    }
    oled.clearToEOL();
  }
}
```

**Pull request closed without merging**
